version: "3.8"

# Production environment override
services:

  php:
    build:
      context: .
      target: php_prod
    volumes:
      - ./SalineAcademyBackend:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  node:
    build:
      context: .
      target: app_node_dev
    volumes:
      - ./SalineAcademyFrontend:/usr/src/app

  caddy:
    build:
      context: .
      target: caddy_prod
    volumes:
      - ./SalineAcademyBackend/public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
