name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true

      - uses: Mysterken/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: hetic-projects.arcplex.tech
          ssh_port: 9122
          ssh_private_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.DEPLOY_USER }}
          docker_compose_prefix: saline
